layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: C#
    web_url: https://github.com/topics/csharp
    image_url: https://raw.githubusercontent.com/github/explore/7f96d7ea34ea0b21f159792a6a8f43b716b33379/topics/csharp/csharp.png

  - name: .Net
    web_url: https://github.com/topics/dotnet
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/dotnet/dotnet.png

  - name: Gradle
    web_url: https://github.com/topics/gradle
    image_url: https://raw.githubusercontent.com/github/explore/e63ac6ef59c5c316574b0d31942f0534e51265a8/topics/gradle/gradle.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/docker/docker.png

  - name: Matlab
    web_url: https://github.com/topics/matlab
    image_url: https://raw.githubusercontent.com/github/explore/a30f3510d1700a60961fb4960d4293455a5e9de4/topics/matlab/matlab.png